var namespace_twilio_1_1_rest_1_1_voice_1_1_v1_1_1_dialing_permissions_1_1_country =
[
    [ "HighriskSpecialPrefixInstance", "class_twilio_1_1_rest_1_1_voice_1_1_v1_1_1_dialing_permissions_1_1_country_1_1_highrisk_special_prefix_instance.html", "class_twilio_1_1_rest_1_1_voice_1_1_v1_1_1_dialing_permissions_1_1_country_1_1_highrisk_special_prefix_instance" ],
    [ "HighriskSpecialPrefixList", "class_twilio_1_1_rest_1_1_voice_1_1_v1_1_1_dialing_permissions_1_1_country_1_1_highrisk_special_prefix_list.html", "class_twilio_1_1_rest_1_1_voice_1_1_v1_1_1_dialing_permissions_1_1_country_1_1_highrisk_special_prefix_list" ],
    [ "HighriskSpecialPrefixPage", "class_twilio_1_1_rest_1_1_voice_1_1_v1_1_1_dialing_permissions_1_1_country_1_1_highrisk_special_prefix_page.html", "class_twilio_1_1_rest_1_1_voice_1_1_v1_1_1_dialing_permissions_1_1_country_1_1_highrisk_special_prefix_page" ]
];